### ISSUE TITLE
Screen rotation does not work with nvidia

### ISSUE THREAD

**Issue by alexandru-calinoiu** [Askannz/optimus-manager#105]
**Describe the bug**
When I try to rotate the screen, X will crash and I have to restart.

**System info**
Please include :
- Arch
- Gnome
- GDM
- Thinkpad X1 Extreme

**Comment by Askannz** [comment]
I can't do much without any log. But it's unlikely that this bug comes from optimus-manager anyways : all it does is set up the X server and appropriate GPU drivers, everything that happens after that is beyond its control.

If you really think this could be an optimus-manager bug, start by making sure you can't reproduce the issue without it (by manually [setting up the Nvidia GPU](https://wiki.archlinux.org/index.php/NVIDIA_Optimus)).

**Comment by alexandru-calinoiu** [comment]
Will investigate further with nvidia
