### ISSUE TITLE
Screenlocking does not work with nvidia

### ISSUE THREAD

**Issue by alexandru-calinoiu** [Askannz/optimus-manager#106]
**Describe the bug**
When switching to nvidia screenlocking does not work anymore

**System info**
Please include :
- Arch
- Gnome
- GDM
- X1 extreme

**Logs**
Are they relevant?

**Comment by Askannz** [comment]
I can only tell you the same thing as for your other issue (https://github.com/Askannz/optimus-manager/issues/105) : screen locking is outside of the control of optimus-manager so it's very unlikely the problem comes from it.

If you want to troubleshoot, start by removing optimus-manager and set up a manual Xorg configuration for the Nvidia GPU. If you can't reproduce the bug that way but it's still there if you install optimus-manager again, re-open this issue.
