### ISSUE TITLE
[Question] Confusion about hybrid mode

### ISSUE THREAD

**Issue by Algebro7** [Askannz/optimus-manager#153]
Hello,

I have an XPS 7590 with a cannon-lake CPU and GTX 1650, so I think this model should support PRIME offloading and the new dynamic power management features. I've got PRIME offloading working and I was curious, assuming I enable both the new power management features (which I havent figured out yet) and PRIME offloading, what are the benefits of using `optimus-manager` in hybrid mode vs just using PRIME on its own? It seems like if the card is handling the power management then `optimus-manager` wouldn't really do anything, is that correct?

Thanks!

**Comment by niciuffo** [comment]
I haven't tested it yet but with PRIME your video outputs likely won't work. Optimus-manager would still be useful to quickly switch to nvidia mode in those cases when you need video output.
There's also some GPUs that don't fully power down even with PRIME, but stay in a low power state thus consuming battery.

**Comment by Algebro7** [comment]
> but with PRIME your video outputs likely won't work.

Do you mean my HDMI port for example? The laptop display on the 7590 is connected to the intel graphics and seems to be working ok without optimus-manager.

**Comment by niciuffo** [comment]
Yes, the HDMI port probably won't work under Hybrid mode, at least that's what I read.

**Comment by rodolpheh** [comment]
On my side, hybrid mode makes my battery last longer than using the intel mode (because the nouveau driver doesn't enable the low power state for the NVIDIA GPU). PRIME offloading is not yet operative on my computer as I didn't find time to rebuild xorg-server with the PRIME offloading patches (see [this doc](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html)) but I guess that if you're using the hybrid mode and want to launch a software on the GPU (let's say a video game), you can do so by adding the proper environment variable to the command line (`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`). As for the HDMI output, I can see it in `xrandr --listproviders` but can't set it (I have a `BadValue (integer parameter out of range for operation)` error).

**Comment by Askannz** [comment]
@Algebro7 
> what are the benefits of using optimus-manager in hybrid mode vs just using PRIME on its own?

Basically what @niciuffo said. optimus-manager is still useful for the cases where you want to use external outputs but they are wired to the Nvidia card.

If you are lucky enough that Prime offloading works, power management in the Nvidia driver works too, and outputs are wired to the Intel card directly, then you probably don't need optimus-manager :slightly_smiling_face:

**Comment by Askannz** [comment]
> Yes, the HDMI port probably won't work under Hybrid mode, at least that's what I read.

It depends on the laptop model, actually. Some laptops have external outputs wired to the Nvidia chip, other have them wired to Intel. In the last case, they can work in Intel mode or even without using optimus-manager at all.

**Comment by Askannz** [comment]
Closing since the original question has been answered.
