### ISSUE TITLE
bbswitch kernel lockup due to premature gpu switch off.

### ISSUE THREAD

**Issue by blmhemu** [Askannz/optimus-manager#158]
**Describe the bug**
bbswitch working in i3 (`sudo modprobe bbswitch load_state=0` actually reduces power consumption and /proc/acpi/bbswitch shows off )
But when using with optimus-manager :
  * If startup is intel, it does not start, stays there without anything (probably due to kernel lockup)
  * If startup is nvidia, then everything works, but when switched to intel using `optimus-manager --switch intel` point "1" happens, the cursor stops blinking and stays there forever after logging out with a blank screen.

I have gone through your code a bit, and it seems that you are switching off gpu (using bbswitch) before starting X (To my understanding, correct me if wrong), which is causing kernel lockup. I was thinking that if bbswitch power off can be done AFTER starting X, then things might work. Also when shutting down, bbswitch must power gpu on before stopping lightdm (or X).

Also just so that you know, I have tried many acpi_osi kernel params with no use.

**System info**
Please include :
- Archlabs
- i3
- LightDM
- Aero 15X - i7-8750H & GTX 1070 Max-Q
- latest stable release (optimus-manager)

**Logs**
https://pastebin.com/ztiv3uWf : This log is when startup is set to intel.
https://pastebin.com/zQdRFsaF : This log when startup is set to nvidia.

Note that in nvidia mode X.conf file is being written and X is working. But in intel mode its gets stuck at power off.

**Comment by Askannz** [comment]
> it seems that you are switching off gpu (using bbswitch) before starting X

Correct.

What you're describing sounds exactly like a classic case of ACPI lockup. The X server tries to poke the Nvidia card at startup, but since it's turned off and the ACPI implementation is broken, the whole system freezes up.

Turning the card off _after_ the server has started might work indeed, but then the system will likely freeze again if any program tries to access the Nvidia GPU.

Here's what you can do to confirm the issue:

1. Set `switching=none` in the config file and reboot. Try switching to intel and see if it hangs again.

2. If it doesn't hang, power off the GPU with `sudo modprobe bbswitch load_state=0` and check it's actually off with `cat /proc/acpi/bbswitch`.

3. If it still doesn't hang, try running a program that pokes the Nvidia GPU, like `lspci`.

If you run into a hang after step 2 or 3, then it's likely the ACPI issue. If no acpi_osi helps, then try setting `pci_remove=yes` in the config file.

**Comment by blmhemu** [comment]
Hey ! Thanks for the reply.

I have tried your above steps and here are the answers :
1. No. It does not hang.
2. Yes it is actually off.
3. lspci hangs if "remove_pci" is "false" but it works and outputs pci lanes if it is set to "true".

Yes the device is plagued by acpi issues. Dissassed the acpi code to find the acpi codes which switch my gpu off and also to check what acpi_osi are supported. Tried various acpi_osi codes and none work.

**Comment by Askannz** [comment]
> Also, please look at the below error. [_**Context**_ : Executed `optimus-manager --print-mode` from tty screen (i.e before logging into lightdm greeter.)]
> https://pastebin.com/cKdVannt

Thanks, fixed.

So does the `pci_remove` solution work for you then ? I know it's kind of an ugly hack but there's not much else I can do.

**Comment by blmhemu** [comment]
Hey !
Somehow [system76-power](https://github.com/pop-os/system76-power) worked for switching gpu.
Previously when using optimus-manager with bbswitch, only gpu is switched off, the nvidia hdmi audio still remains active, which ***might*** be causing the kernel lockup. But when using system76-power, both are deactivated.

**Comment by blmhemu** [comment]
Hi @nwildner - I understand, but I am not actively working on this setup / machine. Please feel free to close this issue.
