### ISSUE TITLE
second display not working

### ISSUE THREAD

**Issue by estebanx64** [Askannz/optimus-manager#162]
**Describe the bug**
Until 1 month ago the secondary screen was working when configuring intel with nouveau backend.

Currently it doesn't work anymore and I'm forced to always start with nvidia if I want to connect a secondary display.

**System info**
- Archlinux 5.3.5-arch1-1-ARCH
- KDE
- SDDM
- Acer predator helios 300
- latest stable release optimus-manager

**Comment by Askannz** [comment]
I need logs to debug this.

**Comment by michaldybczak** [comment]
@estebanx64, which driver do you use for Intel? Intel or Modesetting?

My HDMI is connected to Nvidia directly and only when using Modesetting I can get the secondary screen working. With Intel drivers - not happening. Maybe it's the same by you?

**Comment by TheodoreT** [comment]
@michaldybczak quick question, how is it possible to have a secondary screen working while you are on modesetting. Supposedly it should not be working with modesetting unless you switch to nvidia (this is also in my case), since the HDMI is hard wired to nvidia directly and the recent prime offloading is not supporting multiple screens yet.

**Comment by michaldybczak** [comment]
I have no idea, it just works with Modesetting and HDMI wired to Nvidia in my case. Just try it.
For years I couldn't make the secondary screen work on Intel just because I had on Manjaro Intel/Nvidia non-free drivers, but now that I have Modesetting(free) and Nvidia (non-free), it just works.

**Comment by TheodoreT** [comment]
@michaldybczak thanks for the feedback. Unfortunately no luck here, are you sure that your HDMI output is wired to nvidia because it is still does sum up.

**Comment by michaldybczak** [comment]
Hmm... Now that I think about it deeper I might have been wrong. My HDMI is on the back where the battery is, so the NVIDIA card must be somewhere else then.
I always assumed that the HDMI didn't work with intel and only with Nvidia because it was attached to nvidia (hence the weird positions of the output) but maybe it was because of the intel drivers that didn't cope with the hardware correctly from some reason.

I tried in the past some solutions that in theory should work with HDMI attached to Nvidia and had no luck. 

There was some config that needed to be set manually after recognizing screen numbers or names or whatever. It should be findable by the search engine.

**Comment by michaldybczak** [comment]
@estebanx64, which mode you are talking about? I know now that in Hybrid mode there is no output to secondary monitor and that is because this isn't implemented yet, so we can't do anything about it aside waiting.

As I said above, in Intel Modesetting and Nvidia mode multimonitors work.
