### ISSUE TITLE
KDE session sometimes freezes to restart after switch from intel to nvidia

### ISSUE THREAD

**Issue by edneyhelene** [Askannz/optimus-manager#17]
Hello there, using manjaro kde here, after your last update sometimes when i do switch to nvidia the xorg closes and when it restarts kde freezes  after display the wheel indicating that its loading, doesnt happens all the time anyways, just reporting to see if maybe there is some issue with the latest release? thanks \o

**Comment by Askannz** [comment]
I just pushed version v0.4 to AUR, can you test if the problem persists with this one ? It includes some extra fixes to try to deal with nvidia's randomness.

If the bug is still there, please do the following : reproduce the bug, then reboot your computer and post the outputs of `journalctl -u display-manager -b-1` and `journalctl -u optimus-manager -b-1`.

**Comment by edneyhelene** [comment]
Great, problem solved, thank you so much \o looks like the problem is totally gone \o
