### ISSUE TITLE
Steam games on hybrid mode do not switch to NVIDIA GPU automatically

### ISSUE THREAD

**Issue by yenson-lau** [Askannz/optimus-manager#171]
**Describe the bug**
Although I am able to utilize NVIDIA graphics for Steam games when I switch to NVIDIA mode, I am not able to get the same to happen in Hybrid mode.

**System info** 
- [`inxi`](https://forum.manjaro.org/t/dump-your-inxi-fxzc0-here-and-bookmark-it/8298/631)
- `optimus-manager` version 1.2.2

**Comment by Askannz** [comment]
Offloading doesn't happen automatically, there are a couple of environment variables to set first. See http://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html.

TL;DR: set your launch options in Steam to

```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only %command%
```

I should make the README more clear about that.

**Comment by yenson-lau** [comment]
Oh wow that worked! Thanks so much for the quick response; I'm not used to dealing with these things.

I guess since the environment variables are restricted to the specific screen, there is no way to set the variables at launch?

Thanks again.

**Comment by Askannz** [comment]
Hi, very late reply, but if you can check out this Arch Wiki page : https://wiki.archlinux.org/index.php/Environment_variables

Setting the variables in `/etc/environment` may do the trick, but then you're offloading _every_ OpenGL/Vulkan application, which isn't necessarily what you want.

Another option could be to edit the .desktop file of Steam and add them there (so that they're set before Steam launches).

**Comment by Askannz** [comment]
Added a [dedicated wiki page](https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode) for GPU offloading, hopefully that should clear things up.
