### ISSUE TITLE
optimus-manager broken by Python 3.8 update (DistributionNotFound, daemon doesn't start)

### ISSUE THREAD

**Issue by blackace306** [Askannz/optimus-manager#174]
Now to be fair, I do have the testing repos enabled in my Arch system, so this could be an issue already being worked on. However, last night python3.7 updated to python3.8. After that optimus-manager the service stopped working. It wont even load. I have tried downgrading python3.8 back to 3.7 to no avail. I check the journal of the module in systemd-manager and it seems to be throwing up a lot of python errors so thats what is leading me to think that is the issue. I'll include the journal logs here. Hopefully I used pastebin correctly. Any help would be great.

https://pastebin.com/FTWdSn2d

**Comment by blackace306** [comment]
So I'm not really sure what I did that worked, but I recompiled optimus-manager from the AUR. Did the Arch way, makepkg, etc. Not through yay. It through up that it couldn't find usr/lib/python3.7/... I downloaded python3.7 and installed it manually. Then reinstalled optimus-manager again. I used the command interface to switch to nvidia, it switched. Now the service is running just fine (or it seems to be). Wish I could tell you how I fixed it, if I did, but I have no idea what worked.

**Comment by DOGGO20** [comment]
I was gonna say I just recompiled the git package from the AUR after the python 3.8 update and it works just fine. No need to get 3.7 or anything.

**Comment by blackace306** [comment]
I figured that's probably what did it. In any case I'm glad it's working and I learned something for next time this happens.

**Comment by blackace306** [comment]
I kinda thought that was probably what did it. I'm just glad it's again. And I learned something from it for when similar things happen in the future.

**Comment by ArchFeh** [comment]
I also have this issue after upgrade to python 3.8. Recompiled from AUR doesnt work(
optimus-manager.service - Optimus Manager Commands Daemon
   Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-11-15 01:40:18 MSK; 6s ago
  Process: 1027 ExecStartPre=/usr/bin/prime-switch-boot (code=exited, status=0/SUCCESS)
  Process: 1031 ExecStart=/usr/bin/python3 -u /usr/bin/optimus-manager-daemon (code=exited, status=1/FAILURE)
 Main PID: 1031 (code=exited, status=1/FAILURE)

11月 15 01:40:18 archlinux python3[1031]:     working_set = WorkingSet._build_master()
11月 15 01:40:18 archlinux python3[1031]:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _b>
11月 15 01:40:18 archlinux python3[1031]:     ws.require(__requires__)
11月 15 01:40:18 archlinux python3[1031]:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in re>
11月 15 01:40:18 archlinux python3[1031]:     needed = self.resolve(parse_requirements(requirements))
11月 15 01:40:18 archlinux python3[1031]:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in re>
11月 15 01:40:18 archlinux python3[1031]:     raise DistributionNotFound(req, requirers)
11月 15 01:40:18 archlinux python3[1031]: pkg_resources.DistributionNotFound: The 'optimus-manager==1.2.2' distribution was no>
11月 15 01:40:18 archlinux systemd[1]: optimus-manager.service: Main process exited, code=exited, status=1/FAILURE
11月 15 01:40:18 archlinux systemd[1]: optimus-manager.service: Failed with result 'exit-code'.
~

**Comment by palaboy** [comment]
Same issue here optimus-manager not running exit code error when python 3.8 upgraded, i just reinstall optimus-manager and reboot problem fixed

**Comment by Askannz** [comment]
Yeah the Python 3.8 update kinda broke everything. You need to fully rebuild the package against Python 3.8 (make sure to cleanbuild if you use a AUR helper like yay).

I bumped the $pkgrel on AUR, that should be enough to trigger a full rebuild.

**Comment by nikoloskid** [comment]
Can someone post a fix for this?

**Comment by Kr1ss-XD** [comment]
Just rebuild with Python 3.8. No fix needed.

**Comment by Askannz** [comment]
Both Arch and Manjaro have been using Python 3.8 for a while, I think it's safe to close this issue.

**Comment by hacker1024** [comment]
I got this issue after updating to Python 3.9.0. Rebuilding fixed it again.

**Comment by hacker1024** [comment]
Perhaps a build hook could be added to rebuild the package after a python update?

**Comment by AchmadFathoni** [comment]
same here, after python 3.9.0 service won't start

**Comment by jonathonf** [comment]
Please stop spamming the upstream project with local system issues. This is _not_ an issue with `optimus-manager`.

If you use the AUR then _you_ are responsible for maintaining your local packages, and that includes rebuilding packages which depend on Python when Python is updated (same for Perl, Ruby, etc. etc. etc.).

https://wiki.archlinux.org/index.php/Arch_User_Repository

**Comment by AchmadFathoni** [comment]
@jonathonf how about bumping the AUR release version every python upgrade so it can recompile?
