### ISSUE TITLE
(INFO QUESTION) What means sgi ? any diffrence with intel. Bbswitch vs Noveau

### ISSUE THREAD

**Issue by inzar98** [Askannz/optimus-manager#20]
What is difference with noveau and bbswitch ?

(I need to lower my cpu temp.)

**Comment by Askannz** [comment]
I didn't actually know what SGI means, you made me do some research :grin: 
It means Silicon Graphics, Inc, it's the name of the company who originally developed GLX (the OpenGL extension for the X server). Nvidia provide their own version of that library, that's why the glx vendor is different when you run on the Nvidia GPU.

bbswitch is just a kernel module that sends ACPI messages to the Nvidia GPU to turn it off and on. nouveau is the open-source implementation of the Nvidia driver, and with recent kernels, it is also able to turn the GPU on and off dynamically.

bbswitch is quite old, not supported on newer hardware, and it prevents you from using video outputs connected to the Nvidia GPU in Intel mode (since the card is completely turned off). I suggest not using it unless nouveau doesn't work for some reason.

But whatever you choose, that's not going to have any incidence on your CPU temps.
