### ISSUE TITLE
Question: nouveau

### ISSUE THREAD

**Issue by michaldybczak** [Askannz/optimus-manager#209]
Did I understand correctly that when using nouveau in Intel mode, it theoretically can use Nvidia offloading feature and then it's nouveau handling the GPU?

I understand that nouveau is basically useless for Nvidia but out of curiosity, how one triggers Nvidia on it? Let's assume I already have Configuration 2 : PCI power control with nouveau. What now?

Starting apps in Intel with Configuration 2 : PCI power control with nouveau with `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia` doesn't work, at least for me. In hybrid mode, it works flawlessly thou.

**Comment by Askannz** [comment]
Yes, nouveau also supports offloading. But since it's going through the Mesa stack, you need to set `DRI_PRIME=1` instead (see the [Arch wiki](https://wiki.archlinux.org/index.php/PRIME#PRIME_GPU_offloading)). The other envs `__NV_PRIME_RENDER_OFFLOAD` and `__GLX_VENDOR_LIBRARY_NAME` are only specific to the proprietary driver.

**Comment by michaldybczak** [comment]
Wow, thanks! DRI_PRIME=1 indeed works for Intel Modesetting. It's perfect for some old games that have known issues with Nvidia Driver (like HOMM V). Of course those games also run well on Intel drivers but I suspect that Nouveau will work even better for them, so there are some cases when it can be used. This gives a lot of flexibility.
Thanks!
