### ISSUE TITLE
Tearing on external monitor in nvidia mode

### ISSUE THREAD

**Issue by Zouizoui78** [Askannz/optimus-manager#233]
**Describe the bug**
When in nvidia mode I can use my external monitor connected to HDMI port but the tearing on the **external monitor only** is so awful it's basically unusable for anything beside text editing.
I'm not sure if it is an issue with optimus-manager but there is no tearing if I set the bios to use the nvidia GPU only, so I guess the way the nvidia GPU is set up in nvidia mode is not fully operationnal.
Is there a way to make nvidia mode behave like if I set the bios to use nvidia GPU only ?

Thanks for your time and your work !

**System info**
Please include :
- Arch
- KDE
- SDDM
- Lenovo Y540
- Version of optimus-manager : latest stable release (1.2.2)

**Logs**
Please see attached files :
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4398042/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4398043/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4398044/prime_setup.log)

**Comment by rnd-ash** [comment]
Your using KDE, so try to use [kwin-lowlatency](https://github.com/tildearrow/kwin-lowlatency). That fixed it for me

**Comment by Askannz** [comment]
It's a problem that has plagued KDE+Nvidia for a long time, and isn't specific to optimus-manager. A few things you can try:

* Enable [ForceFullCompositionPipeline](https://github.com/Askannz/nvidia-force-comp-pipeline)

* Go to the Nvidia control panel, "X Server XVideo settings" and make sure it's syncing to the external monitor

* Go to the compositor setting of KDE and fiddle with backend and vsycn options

Closing this issue because there is nothing I can do from the optimus-manager side.
