### ISSUE TITLE
Suggestion about dynamic startup mode

### ISSUE THREAD

**Issue by Shatur95** [Askannz/optimus-manager#236]
I see that @aouerfelli implemented dynamic startup mode. Thank you, this is really useful feature!
But as for me it is not look very clear, especially for [GUI](https://github.com/Shatur95/optimus-manager-qt) I'm working on. For now this is a startup mode which is inconsistent with `hybrid`, `intel` and `nvidia` because `ac_auto` not a card mode itself, it just picks another mode depending on AC. I suggest to replace `ac_auto_battery_mode` with two options: `dynamic_startup_mode` (it was removed in 216e2801f772c842fb7e68c7c37a9b879e70787d) and `ac_battery_mode` that can accept `intel`, `nvidia` or `hybrid`. And just check battery status at startup if `dynamic_startup_mode` is enabled. This also will be more flexible because it allows use `hybrid` for a normal start and `intel` for a start without ac.

**Comment by Shatur95** [comment]
Any news? It would be nice to make a release with new changes with up-to-date GUI client.

**Comment by Askannz** [comment]
Actually I have been thinking about moving `startup_mode` to the config file entirely. Having it set dynamically with `--set-startup` was a bad idea in the first place.

So how about this: we add 3 options to the config file (taking inspiration from @Kr1ss-XD PR).

* `startup_mode`: can be `intel`, `nvidia`, `hybrid`, `auto`
* `startup_auto_battery_mode`: the effective mode when `startup_mode=auto` and the computer is booted on battery. Can be `intel`, `nvidia`, `hybrid`
* `startup_auto_extpower_mode`: same for AC power.

Alternatively, instead of `startup_mode=auto`, we could have a 4th parameter `dynamic_startup_mode=yes|no`, like you suggested. But it's slightly more confusing for the user IMHO.

Opinions ?

**Comment by Shatur95** [comment]
Absolutely agree. The idea with three options is great.

**Comment by StanczakDominik** [comment]
Just popping in to say I was going to suggest the exact same thing we're discussing in this issue! Kudos :laughing: Looking forward to the release implementing it!

**Comment by Kr1ss-XD** [comment]
> Absolutely agree. The idea with three options is great.

:+1: **+1**

**Comment by Shatur95** [comment]
Applied in GUI too. Could you draft a new release?
