### ISSUE TITLE
Which files does optimus-manager write to?

### ISSUE THREAD

**Issue by trusktr** [Askannz/optimus-manager#239]
I'm just wondering, which files optimus-manager write to when I switch GPUs? I'd like to learn a little but about how the configurations work.

**Comment by trusktr** [comment]
When I try modifying settings using the optimus-manager-qt UI, I see that it modifies `/etc/optimus-manager/optimus-manager.conf`, for example when I change the the driver for Intel from modesetting to intel, I see it modifies the file to contain

```
driver=intel
```

But when I select other options, like choosing which driver to use by default for "Startup mode", I don't see where it makes this change.

**Comment by Kr1ss-XD** [comment]
* You may find what you're looking for inside the `/var/lib/optimus-manager/` folder.
* Also, `/etc/X11/xorg.conf.d/10-optimus-manager.conf` is being altered when you switch modes.
* Logs go to `/var/log/optimus-manager/*.log`.

Not 100% sure if I'm missing out something, but I think that should be it.

**Comment by Askannz** [comment]
Yeah, all the "current state" files are in `/var/lib/optimus-manager/`. This includes the next startup mode as well as a few other things. I've been refactoring this part recently, so you may find that the current master version does things differently than the latest release. 

`/etc/X11/xorg.conf.d/10-optimus-manager.conf` is the only other file (besides logs) outside of this folder that is written dynamically for GPU switches (because Xorg needs to read it).

**Comment by trusktr** [comment]
Awesome, thank you!
