### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by noctuid** [Askannz/optimus-manager#241]
First of all, thanks a lot for this. I was previously using bumblebee and switched to nvidia-xrun for better performance. It was buggy an I occasionally had X crashes (hoping maybe that will go away with optimus-manager). The fact that I can use intel mode but still connect to monitors is great. To confirm, with `switching=nouveau` and intel mode, the GPU is only used for connecting to monitors?

I have a couple other questions/suggestions as well. Is there a reason a separate file is used for the startup mode instead of optimus-manager.conf (would be nice if I could just put it in the config)? Also, could there be a version of `optimus-manager --switch` that doesn't need X running? I don't use a display manager and would prefer to be able to manually quit to the tty and run a single command instead of running `optimus-manager --switch` while X is running and then running `prime-switch` after quitting X.

**Comment by noctuid** [comment]
Also, the documentation doesn't make it sound like `prime-offload` dosen't need to be root, but it does (otherwise it can't write to `/var/lib/optimus-manager/tmp`, and maybe other stuff breaks). Not sure if the documentation just needs to be made more clear or if it would be possible to not have to run `prime-offload` as root (that would be great).

**Comment by Askannz** [comment]
> To confirm, with `switching=nouveau` and intel mode, the GPU is only used for connecting to monitors?

Correct. Well, technically you can also use it for rendering (using DRI_PRIME offloading) but it's kinda pointless given how slow nouveau is. 

> Is there a reason a separate file is used for the startup mode instead of optimus-manager.conf (would be nice if I could just put it in the config)?

I wanted the users to be able to set their startup mode with as little friction as possible (using just `optimus-manager --set-startup`), but in retrospect I agree it's a bit silly. Maybe in a future release this will be in the config file instead, but for now I don't want to break people's setups.

> Also, could there be a version of optimus-manager --switch that doesn't need X running?

To be honest I haven't given much thought about running optimus-manager without a display manager, and it's true the ergonomics could be improved a lot there. I'll look into it.

> Also, the documentation doesn't make it sound like prime-offload dosen't need to be root, but it does

Yes, that's a bug with the -git version (see https://github.com/Askannz/optimus-manager/issues/243). Will fix it soon so that prime-offload does not need root permissions.

**Comment by noctuid** [comment]
> Maybe in a future release this will be in the config file instead, but for now I don't want to break people's setups.

Maybe you could keep `--set-startup` and prioritize the file it creates over the config file for backwards compatibility.

**Comment by Askannz** [comment]
`--set-startup` is now deprecated in v1.3 and replaced with a config file option.
