### ISSUE TITLE
Question about nvidia-enable.sh

### ISSUE THREAD

**Issue by michaldybczak** [Askannz/optimus-manager#249]
When troubleshooting hybrid graphic issues on Manjaro forum for other users, I frequently come across some weird lines in optimus-manager logs, namely:
```

Running /etc/optimus-manager/nvidia-enable.sh
ERROR : cannot run /etc/optimus-manager/nvidia-enable.sh. Continuing anyways. Error is : Failed to execute '/etc/optimus-manager/nvidia-enable.sh' : bash: /etc/optimus-manager/nvidia-enable.sh: No such file or directory
```

Aside of that, the rest looks normal and sometimes the error disappears with time. I checked my system and I don't see  `/etc/optimus-manager/nvidia-enable.sh`, but on my system optimus-manager won't try to run it either so everything is OK. So why this is showing for others? What issue it may indicate?
Thank you

**Comment by andrhua** [comment]
`optimus-manager` tries to run` nvidia-enable(disable).sh` prior to card enabling (after its disabling) if `switching` setting in configuration is set to `none`. By default these files indeed are non existent.

**Comment by Askannz** [comment]
Ok, this bug has been driving me nuts for a while. I could never reproduce it on my Archlinux machine.

Turns out it's a packaging issue in Manjaro. For some reason they repackaged optimus-manager as version `1.2.2-2.2` (with an extra `.2`) and their PKGBUILD does not include `nvidia-enable.sh`. No idea why they did that, you should take it to them.

In the meantime, it's safe to ignore this error.

**Comment by michaldybczak** [comment]
I created a topic to turn Manjaro devs attention to this problem:

https://forum.manjaro.org/t/optimus-manager-on-manjaro-is-missing-nvidia-enable-disable-sh-packaging-problem/140133
