### ISSUE TITLE
Loginctl to change seat

### ISSUE THREAD

**Issue by justrobd** [Askannz/optimus-manager#25]
Hi, I was looking into different ways that don't necessarily consist of restarting the display-manager or restarting X.  Specifically I was interested if it would be possible to use the loginctl command. 
```bash
 loginctl attach [Seat Name] [Device...]   
```
According, to the loginctl's man page it is possible to attach the device like a graphics card to a specific seat. Then it is possible to use loginctl  to flush the that device using 
```bash
loginctl fluh-devices
```
I'm not sure how to exactly implement this myself. I thought maybe I can give you the idea and if you had time you can run with it. I'm will to try to do some testing if you need help or whatever. Let me know if I'm misinterpreting the use of loginctl.

**Comment by Askannz** [comment]
Sorry for the late reply.

So after reading your suggestion I experimented a bit with `loginctl`, and I almost bricked my computer :sweat_smile: 

Turns out Linux is really not happy when you attach one of your GPUs to a different seat while using it. And apparently the change is persistent, so even after rebooting the computer, I couldn't use my GPU until I reattached it to the default seat. Be careful if you try it yourself.

Anyway, thank you for your suggestion. It's definitely an interesting feature that I didn't know about. But I don't think it could really help with Optimus. If I understand correctly, your idea is to have two seats and one GPU attached to each seat ?
That's not going to work because the built-in screen of your laptop is hardwired to the Intel GPU. So even in Nvidia mode, one the Nvidia seat needs access to both GPUs.

It could work if you plug in an external monitor, though. Assuming both seats can use the same mouse and keyboard (or if you are willing to plug in additional ones).

**Comment by justrobd** [comment]
Sorry to here that it almost bricked you computer. That really sucks. You got it right I was thinking starting two seats with one attached to the GPU. I keep forgetting that the display is hardwired to the Intel GPU. Well it was an idea that failed. I'm going to keep using optimus-manager anyways it seems to working really well for me. Thanks for the work on this project.

**Comment by Askannz** [comment]
Haha don't worry, it's not your fault. No damage done.

Well, closing this issue for now, thanks for your input.
