### ISSUE TITLE
Laptop won't switch off

### ISSUE THREAD

**Issue by mpanarin** [Askannz/optimus-manager#250]
**Describe the bug**
Can't shutdown my laptop, it just hangs and I have to force it.
basically, same effect that is mentioned in https://github.com/Askannz/optimus-manager/issues/46

Relevant kernel log with the error: https://pastebin.com/d9TVR1vB

**System info**
Please include :
- Manjaro
- KDE
- SDDM
- Razer Blade Stealth late 2019
- optimus-manager 1.2.2-2.2

**Logs**
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4538375/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4538377/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4538378/prime_setup.log)

**Comment by Askannz** [comment]
Looks like bbswitch is causing the kernel crash, have you tried disabling bbswitch in the config file ?

This is likely a bug with bbswitch not supporting your laptop model (since it's very recent). Try with other power management options, or see if you can reproduce this bug without optimus-manager (install only bbswitch) and report it to https://github.com/Bumblebee-Project/bbswitch.

**Comment by mpanarin** [comment]
Switching to kernel 5.7 and power management to Nvidia with hybrid mode fixed the issue
