### ISSUE TITLE
When switching to or booting nvidia mode, I have to restart plasmashell for it to work

### ISSUE THREAD

**Issue by noir-Z** [Askannz/optimus-manager#267]
I'm on Manjaro (Kernel 5.4) and installed the KDE (5.18.5) flavour through Architect. 

Switching between modes works fine for me. 
However, when using the nvidia mode, initially the plasmashell always kind of fails to launch properly. It never shows the taskbar until I manually restart plasmashell through kquitapp5 and kstart5 plasmashell, it does display a wallpaper though.

I set up my external monitor as the primary display and this causes no issues in intel mode.
A few observations while on nvidia: 
The external monitor (primary display) shows no background (black) but i can move the mouse on it and have windows on it. The laptopscreen does show its wallpaper.

After restarting plasma, everything goes back to normal, Taskbar shows up, wallpapers are displayed correctly.

When switching to or booting intel, sddm extends to both monitors, showing a correctly sized login prompt on both screens, with the mouse being able to move between the two displays.

When switching to or booting nvidia, sddm will mirror the primary (external) monitors screen onto the internal display, thus only showing a part of it, since the external monitors resolution is bigger.

All of this leads me to believe that it is some kind of configuration problem but due to my limited knowledge i don't really know where to start.

**Comment by noir-Z** [comment]
Problem only occurs when the external monitor is set as primary. When the laptop screen is set as primary kde starts normally.

**Comment by Askannz** [comment]
Hmm I don't know, I also use KDE with an external monitor as the primary one and it's working fine.

My first guess would be some kind of conflict between optimus-manager and the screen setup utility of KDE. You can enable/disable it in KDE settings -> Startup and Shutdown -> Background Services -> KScreen 2. But even if that's the case, I have no idea how to debug this.

**Comment by noir-Z** [comment]
Do you also have both monitors enabled? I'm one of those cases where the hdmi-output is not connected to the nvidia card.
Is Kscreen not run after sddm? Since sddm is already wonky when switching to nvidia i would assume that it could be xorg conf problem, or is that not possible?

**Comment by noir-Z** [comment]
I just tried having only the external monitor enabled and set as primary, same result.

**Comment by Askannz** [comment]
> Do you also have both monitors enabled? I'm one of those cases where the hdmi-output is not connected to the nvidia card.

Yes I have both enabled, however the HDMI output of my laptop is wired to the Nvidia card directly, unlike yours.

Could you test the branch `disabled_prime` and see if the issue still occurs ? I just want to check if the issue has anything to do with the xrandr setup applied by optimus-manager for Prime display offloading. This branches disables it completely, which will cause your laptop monitor to become blank when switching to nvidia. But since you also have an external monitor, that should be fine.

You can use this PKGBUILD for the branch: https://github.com/Askannz/optimus-manager/tree/disabled_prime/package

**Comment by nwildner** [comment]
Closing this case since the original reporter didn't came back even with the developer providing a specific branch for this to be tested.

@noir-Z , please use a recent version of your distribution with updated linux kernel, nvidia driver and use the `optimus-manager-git` package since a lot has changed from when this case was originally reported.

This issue isn't active for the last 4 years ago and a lot has changed in many aspects of multiple software so, we'll be closing this case. We're dealing with backlog here to try to keep `optimus-manager` in a good shape and active as a project.

Have a nice week ahead.
