### ISSUE TITLE
prime-run failes in hybrid mode

### ISSUE THREAD

**Issue by sobhan87068** [Askannz/optimus-manager#304]
hi,
i'm using manjaro KDE with kernel 5.4 LTS on an Acer aspire with intel i7 9750H and Nvidia Geforce GTX 1650 i have installed the hybrid graphics drivers, optimus-manager and optimus-manager-qt.
Until yesterday, everything was working fine but suddenly i have issues with using nvidia graphics in hybrid mode.
Any Application i try to run with Dedicated GPU gives the following error:

`XIO:  fatal IO error 17 (File exists) on X server ":0"
      after 52 requests (52 known processed) with 6 events remaining.`

i have tried:
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only"` options and `prime-run` with the same error.
but If I switch the mode to Nvidia everything works fine

**Comment by nwildner** [comment]
Hello @sobhan87068 . Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Let me know if this issue is still relevant to you ok?

Have a nice week.
