### ISSUE TITLE
Can't switch back to intel(black screen)

### ISSUE THREAD

**Issue by Meshikhah** [Askannz/optimus-manager#32]
After installing navida driver i encounter two problem.first after booting up with nvidia resolution changed everything get bigger.
Second problem after switching back to intel and everything is black i have to switch to nvidia with the first problem.
I am using manjaro cinnamon .

**Comment by Askannz** [comment]
> first after booting up with nvidia resolution changed everything get bigger.

Not sure if I understand your problem correctly, but try removing `/etc/X11/xorg.conf` if it exists. It is autogenerated by `nvidia-xconfig` but filled with outdated stuff and can cause the X server to start in low resolution.

For your second problem, I'm aware of the issue, but haven't found a proper fix for it yet. In the meantime, you can try setting the power management method to `bbswitch` or disabling modesetting in Intel mode.

**Comment by Askannz** [comment]
Do you still have the issue ?

**Comment by Ahuri3** [comment]
I am having issues switching back. It seems a bit random but I can give some info. I'm not sure I have the same issue @Meshikhah is having but the ticket is so aptly named and he hasn't given much information.

### Description of the issue : 

When I boot I am in `Intel mode` and all works well. Here is the xorg log file : 
[no-problem-intel.xorg.log](https://github.com/Askannz/optimus-manager/files/2879022/no-problem-intel.xorg.log)

I can try to switch to nvidia and it works (not every single time but usually). Here is the xorg log file of : 
[no-problem-nvidia.xorg.log](https://github.com/Askannz/optimus-manager/files/2879024/no-problem-nvidia.xorg.log)

Once I am in nvidia mode and I try to switch back I get an issue : GDM load fine but after I try to login Xorg crashes and I am sent back to the login screen on GDM. 

Here is the Xorg log file : 
[problem-intel-xorg.log](https://github.com/Askannz/optimus-manager/files/2879040/problem-intel-xorg.log)

An excerp from the log file : 
```
[   221.869] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   221.869] xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[   221.869] (EE) open /dev/dri/card0: Permission denied
[   221.869] (WW) Falling back to old probe method for modesetting
[   221.869] (EE) open /dev/dri/card0: Permission denied
[   221.869] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[   221.869] (EE) Screen 0 deleted because of no matching config section.
[   221.869] (II) UnloadModule: "modesetting"
[   221.869] (EE) Device(s) detected, but none match those in the config file.
[   221.869] (EE) 
Fatal server error:
[   221.870] (EE) no screens found(EE) 
[   221.870] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[   221.870] (EE) Please also check the log file at "/home/lferlin/.local/share/xorg/Xorg.1.log" for additional information.
[   221.870] (EE) 
[   222.378] (EE) Server terminated with error (1). Closing log file.
```

No the interesting part : If I switch tty and connect via terminal I can fix the situation by running `optimus-manager --switch intel` a second time. After the second switching attempt it seems to work flawlessly. Here are the last Xorg log file : 
[again-no-problem.log](https://github.com/Askannz/optimus-manager/files/2879046/again-no-problem.log)



### General informations : 

First of all here is my optimus configuration : 
[optimus-manager.conf.txt](https://github.com/Askannz/optimus-manager/files/2878999/optimus-manager.conf.txt)

I have a laptop with an `Intel Core i7-8750H` and a `GTX 1070 Max-Q` 
The drivers I use for nvidia are : 
```
pacman -Q | grep nvidia 
lib32-nvidia-utils 415.27-1
nvidia 415.27-7
nvidia-settings 415.27-1
nvidia-utils 415.27-1
```

And for Intel : 
```
vulkan-intel 18.3.3-2
xf86-video-intel 1:2.99.917+859+g33ee0c3b-1
lib32-mesa 18.3.3-1
mesa 18.3.3-2
```
My xorg version is `xorg-server 1.20.3-1`
I use gnome and GDM : 
```
gdm 3.30.2-2
libgdm 3.30.2-2
```

I am on the aur package of optimus-manager (v 0.7) : 
```
optimus-manager 0.7.1-1
```

I had to forbit GDM from using Wayland to get the switching to work.

I also set the intel driver mode to ` intel` instead of modeseting because it was causing a lot of errors in the Xorg.X.log files (`flip queue failed: Invalid argument`).

Finally I used to use bumblebee and it worked fine. I disable the service and remove the package before trying to use optimus-manager.

Regards,

Leo

**Comment by Askannz** [comment]
Could you test the latest Git version and see if the problem persists ?
This version introduces some major changes to the way optimus-manager works, so you need to reboot after upgrading to make sure everything is reloaded up properly.

**Comment by Ahuri3** [comment]
I hadn't tried it since I made the comment, but I just tried and it worked !

Thank you so much !

**Comment by Askannz** [comment]
Great ! :)
