### ISSUE TITLE
after update GDM can fail to auto-restart

### ISSUE THREAD

**Issue by cyrstem** [Askannz/optimus-manager#322]
**Describe the bug**
for some reason after the update  now i have to 
 switching back and forth between TTYs, then back to TTY 1 or TTY 7 
(for some reason, GDM can fail to auto-restart the X server of the login screen until you have done that)is there a fix for this ?

**System info**
manjaro 
gnome 
gdm-prime
razerblade-15 2018

**Comment by nwildner** [comment]
Hello @cyrstem 

 Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Let me know if this issue is still relevant to you ok?

Have a nice week.
