### ISSUE TITLE
Laptop freezes with acpi_call method

### ISSUE THREAD

**Issue by FPSUsername** [Askannz/optimus-manager#331]
**Describe the bug**
When I use acpi_call as a switching method, the laptop completely freezes after finding the correct call.

I rebooted in tty mode and saw that no "cache" file had been created under `/var/lib/optimus-manager/persistent/` <sup>1</sup>.
I created my own file in `acpi_call_strings.json` with the content:
`[["\\_SB.PCI0.PEG0.PEGP._OFF", "\\_SB.PCI0.PEG0.PEGP._ON"]]`
When booting the system, I see that the `AE_NOT_FOUND` messages aren't there anymore, yet the system still freezes.

My workaround for now is to make use of the configuration files:
```bash
#  nvidia-enable.sh
echo '\_SB.PCI0.PEG0.PEGP._ON' | sudo tee --append /proc/acpi/call > /dev/null
sudo rmmod acpi_call
sleep 5
```
```bash
# nvidia-disable.sh
sleep 5
sudo modprobe acpi_call
sleep 10
echo '\_SB.PCI0.PEG0.PEGP._OFF' | sudo tee --append /proc/acpi/call > /dev/null
```
**System info**
- Manjaro
- KDE
- SDDM
- Dell XPS 15 9560
- optimus-manager-git
- Default configuration file, except switching is set to acpi_call

<sup>1</sup> The path and file name are mentioned incorrectly in the [wiki](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#how-to-configure) if you compare it with the [code](https://github.com/Askannz/optimus-manager/blob/master/optimus_manager/envs.py)

**Comment by nwildner** [comment]
Sup @FPSUsername . How are things going?

Is this still reproducible in a more modern install with updated Linux kernel, `acpi` dkms, `nvidia` driver and using the `optimus-manager-git` package?

Looking at the [`acpi_data.py`](https://github.com/Askannz/optimus-manager/blob/master/optimus_manager/acpi_data.py) file, looks like the ACPI string your GPU expect (   `"\\_SB.PCI0.PEG0.PEGP._OFF", "\\_SB.PCI0.PEG0.PEGP._ON"` ) exists since this file was imported to `optimus-manager` so it SHOULD work out of the box but for some reason it's not being correctly sent.

Out of curiosity. If you clear your `acpi_call_strings.json` or move it, what is the JSON file that is generated? What tuple of strings is configured there or is it just empty?

Have a nice day.

**Comment by es20490446e** [comment]
If the issue is still there, update your [UEFI](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=t4gmn) from an [external Windows Live USB](https://www.howtogeek.com/196817/how-to-create-a-windows-to-go-usb-drive-without-the-enterprise-edition/).

If that doesn't fix it, reopen.

**Comment by FPSUsername** [comment]
Unfortunately I'm not using Linux on this laptop anymore. I believe at the time I already was using the latest UEFI provided by Dell (1.24).
A lot of things could have changed in the past 3-4 years, so who knows if it's still an issue.

**Comment by es20490446e** [comment]
Whoops!
