### ISSUE TITLE
Cannot boot with nvidia or switch mode.

### ISSUE THREAD

**Issue by Alonely0** [Askannz/optimus-manager#359]
I'm on Arch Linux with kernel 5.9.14 and with a card Nvidia GTX 1650.

Some hours ago, when booting up my PC, xorg could not start, so I had to boot my recovery partition (it's just a minimal arch installation, that fits in 3gb of my disk. Is for repairing my PC when Nvidia break it, like now). With it, I removed all the config of xorg, and then I could boot my PC up.
When I signed in, I noticed some noise in the blurs, a common signal of problems with Nvidia, and when I looked on my system tray, I saw that I had booted with the integrated intel card.
Then, I tried to switch to Nvidia, but the optimus-manager-qt told me that the `optimus manager.service` was already running, and that I had to execute this
```
sudo systemctl enable optimus-manager
sudo systemctl start optimus-manager
```
After doing that, I tried again, and I got the same error. I thought "Ok, I usually have problems with optimus qt, so I'm going to do it with the terminal"
Then, I ran
```
optimus-manager --switch nvidia
```
And got
```
ERROR: the active card is "intel" but it should be "nvidia".
Something went wrong during the last GPU setup...
Log at /var/log/optimus-manager/switch/switch-20201230T013432.log
Config parsing : error in option "startup_auto_battery_mode" in section [optimus] : invalid value "integrated"
Config parsing : unknown section [amd]. Ignoring.

Cannot execute command because of previous errors.
```
This is the log
```
[16] INFO: # Xorg pre-start hook
[17] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[17] INFO: Requested mode is: nvidia
[17] INFO: Checking for GDM display servers
[880] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[880] INFO: Unloading modules ['nouveau'] (if loaded)
[884] INFO: switching=none, nothing to do
[1007] INFO: Nvidia card not visible in PCI bus, rescanning
[1007] INFO: Rescanning PCI bus
[1060] INFO: Loading module nvidia
[1785] INFO: Loading module nvidia_drm
[3744] INFO: Loaded extra integrated-gpu Xorg options (0 lines)
[3744] INFO: Loaded extra nvidia-gpu Xorg options (0 lines)
[3744] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[3745] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20201230T013432', 'requested_mode': 'nvidia'}
[3745] INFO: Xorg pre-start hook completed successfully.
[14] INFO: # Xorg post-start hook
[14] INFO: Running xrandr commands
[240] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[274] INFO: Writing state {'type': 'done', 'switch_id': '20201230T013432', 'current_mode': 'nvidia'}
[274] INFO: Xorg post-start hook completed successfully.
```
---
Configuration
```
[amd]
DRI=3
driver=modesetting
tearfree=

[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=yes
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=nvidia
switching=none
```

Sorry if my English is a bit rusty or sounds a bit strange or bad.

**Comment by noorbala7418** [comment]
Hello
My problem is same you. ( My kernel was 5.9.11)
But I found solution.
Change your kernel version to 5.8.18.

Good luck.

**Comment by Alonely0** [comment]
Ok. I will downgrade the kernel. If all work again, I'll close de issue.

**Comment by Alonely0** [comment]
I'm looking at the Arch Linux Archive (a.k.a. ALA) and the latest 5.8 kernel is the 5.8.14, and not the 5.8.18, so I'm going to install the 5.8.14.

**Comment by noorbala7418** [comment]
Sorry. I am using Manjaro Linux :)

**Comment by Askannz** [comment]
What's the output of `glxinfo` and `lsmod | grep nvidia` ?

**Comment by ccxex29** [comment]
I have the same issue as yours. I can get inside DM, but only on external monitor (just like what's described in [this faq](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#when-i-switch-to-nvidia-the-built-in-screen-of-the-laptop-stays-black-but-i-can-still-input-my-password-or-use-monitors-plugged-to-a-video-output)).  

I use Artix Linux with SLiM and awesomewm.  
The fix I have come up is using `optimus-manager --switch integrated` after login with nvidia ([auto logout has to be disabled](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#i-do-not-want-optimus-manager-to-log-me-out-automatically)). This way, unexpected and expected cases are both covered and the 'integrated' status is expected on boot (since I tried to use this inside a reboot script).

**Comment by Alonely0** [comment]
> What's the output of `glxinfo` and `lsmod | grep nvidia` ?

I had nvidia drivers installed and working. I changed of Linux distro 1 or 2 weeks ago, and I achieved installing optimus again, but was more difficult than usual.

**Comment by nwildner** [comment]
Hello @Alonely0  Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Let me know if this issue is still relevant to you ok?

Have a nice week.

**Comment by Alonely0** [comment]
Nice weekend to you too, and thank you for the amazing work you do. Unfortunately, the device where I encountered this issue is no longer in my possession, so I won't be able to reproduce it anymore. It does not appear that this has affected many people anyway, so my advice is just to close this issue and reopen it if a duplicate is ever submitted.
