### ISSUE TITLE
no way to uninstsall it 

### ISSUE THREAD

**Issue by happyeggchen** [Askannz/optimus-manager#367]
Don`t know how to uninstall it , installed by setup.py 
debian buster on Asus k53sd

**Comment by Askannz** [comment]
optimus-manager is only for Archlinux-based distros, Debian is not supported.

Also, it needs to be installed through the package manager, not by running setup.py (doing `sudo setup.py` is a really bad idea for any program in general, because it conflicts with the package manager).

`pip uninstall optimus-manager` should uninstall it.
