### ISSUE TITLE
Hybrid mode using 30% of the GPU when a HDMI monitor is connected

### ISSUE THREAD

**Issue by FranLMSP** [Askannz/optimus-manager#370]
First of all, thanks for this nice project! This is the solution that works the best for me.

I have a question. When I'm on hybrid mode and I connect a HDMI monitor, the GPU usage goes to 30% according to `nvidia-smi` (by doing nothing, only with the DE open).

This does NOT happend on Nvidia mode. On Nvidia mode the GPU usage is always 0~5% with the monitor connected.
However I get more performance in games with hybrid mode anyways (lol).

Why does this happend? Is it because the GPU is running at a lower clock speed and `nvidia-smi` thinks that it's being used 30%?

I use Arch Linux with Gnome 3.

**Comment by Askannz** [comment]
> Why does this happend? Is it because the GPU is running at a lower clock speed and nvidia-smi thinks that it's being used 30%?

Yes exactly, this usage number is proportional to the current GPU clock. You can test this yourself, if you launch a light 3D application like glxgears, the clock ramps up and the total usage percentage goes _down_.

As for why there is GPU usage at all, I think that's because the Nvidia GPU needs to copy frames from the iGPU and they can't use dma-buf yet (there was a forum post from Nvidia explaining the whole thing but I lost it).

In any case, it's not something optimus-manager has any control over.
