### ISSUE TITLE
Is it possible to add xorg git support?

### ISSUE THREAD

**Issue by KyunLFA** [Askannz/optimus-manager#374]
Hi, first I just wanna say optimus-manager is a lifesaver and I'm very thankful for everyone developing it. 

I think some users would prefer to use the latest git version of xorg server specially due to how inactive its development is for new stable versions, would it be possible to add support for xorg git? 

At one point I attempted to use xorg git with optimus manager, but an error related to ABI_VIDEODRV_VERSION thwarted my attempt (stable xorg version is 24.1, git xorg is 25.2). Everything would work normally but GPU wouldn't switch to nvidia, if I recall correctly (it was some months ago) it was erroring at prime-offload.

I apologize if I'm asking too much. I'm already on latest git of optimus-manager and I'm very willing to report any issues related to xorg git support in case it's added. Thank you regardless.

**Comment by IronOverheat** [comment]
Upon further reflection I'm unsure if the error was really due to ABI_VIDEODRV_VERSION, perhaps I'm misremembering, I apologize, keep in mind I don't really get what I'm doing 100%.

**Comment by nwildner** [comment]
Hello @KyunLFA . Is this still happening using more recent `optimus-manager-git` versions?

Since the last comment on this case was from 3 years ago and a lot has changed in many aspects of multiple software(nvidia, optimus-manager, linux), we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.
