### ISSUE TITLE
Hybrid mode not working on Dell G5 5587

### ISSUE THREAD

**Issue by Tankettekek** [Askannz/optimus-manager#378]
So I don't really know why, but whenever I switch to hybrid mode, trying to login into KDE doesn't work. I can login but it will just be stuck at the loading splash screen and then crash. 

As stated in the title I have a Dell G5 5587 with a GTX 1060M and an i5. If you need any logs please tell me how to get them.

**Comment by yuky2020** [comment]
Same here  arch linux on G3 3590, gtx 1650 ,same DE (KDE and  SDDM)

**Comment by nwildner** [comment]
Hello @Tankettekek  Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Let me know if this issue is still relevant to you ok?

Have a nice week.
