### ISSUE TITLE
prime-offload makes gnome hang

### ISSUE THREAD

**Issue by eksprestren** [Askannz/optimus-manager#379]
Optimus-manager always needed me type prime-offload to work but now if I type prime-offload gnome hangs.

**Distro:Manjaro**

**DE:GNOME**

**DM:GDM**

**Model:ASUS N56VZ**

**Version:Stable**

Logs:
[switch-20210218T231913.log](https://github.com/Askannz/optimus-manager/files/6009622/switch-20210218T231913.log)

**Comment by nwildner** [comment]
@eksprestren , is this issue still happening on a more modern Linux install and using `optimus-manager-git`? Is this still relevant to you?

Since the last update on this case was from 3+ years ago, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.
