### ISSUE TITLE
Which graphics driver package to use with linux-lts kernel?

### ISSUE THREAD

**Issue by xXToYeDXx** [Askannz/optimus-manager#381]
I'm aware this is an issue tracker but I can't seem to find any place to ask questions or to ask for clarifications. (Forums, discord etc) I apologize if this is not the appropriate place to ask this but it's the only place I can find.

I run the linux-lts kernel in Arch. The installation instructions note that you can use either the nvidia or nvidia-dkms driver package. However, the arch repo contains nvidia-lts for anyone who is using the lts kernel. dkms is said to be used by anyone using a custom kernel, however I am not. Do I still need the nvidia-dkms package or will the nvidia-lts package also work?

**Comment by Kr1ss-XD** [comment]
The DKMS driver will work with _any_ kernel, as it is built locally everytime a new kernel (or `nvidia-dkms` itself) is installed or updated. It's built against every installed kernel and is hence recommended if you use a custom kernel or multiple kernels. `nvidia-lts` on the other hand is a package that's pre-built specifically for `linux-lts`.

So you can use either one of those, though if you only ever run the lts kernel, I'd recommend `nvidia-lts` since it is prebuilt and saves you some time on updates.

**Comment by xXToYeDXx** [comment]
I should have been more clear. I was asking specifically about optimus-manager. The instructions for optimus-manager state to use either Nvidia (assuming mainline stable kernel, linux package) or nvidia-dkms (assuming with custom kernel or lts kernel). However, since the installation instructions for optimus-manager specifically state "nvidia" or "nvidia-dkms", are there any issues with GPU switching when using the "nvidia-lts" package?

**Comment by Kr1ss-XD** [comment]
Oh, I see.

No, there shouldn't be any problem using optimus-manager on lts. It has basically the same features/configuration as mainline.

**Comment by xXToYeDXx** [comment]
Thanks for the clarification. I'll try using the lts driver package. I just wonder why it was excluded from the instructions for optimus-manager. Here I thought I had no choice but to either use mainline kernel or dkms driver package with lts kernel for optimus to work.

**Comment by Kr1ss-XD** [comment]
> I just wonder why it was excluded from the instructions for optimus-manager. Here I thought I had no choice but to either use mainline kernel or dkms driver package with lts kernel for optimus to work.

Agreed.
