### ISSUE TITLE
Different DPI when switching from Integrated to Nvidia

### ISSUE THREAD

**Issue by g0r3** [Askannz/optimus-manager#400]
Hi,

I am using a Laptop with Intel IGP and an Nvidia MX150 on Archlinux/KDE. I encouter the issue, that some of the UI elements seem to be smaller when I switch from IGP to Nvidia. For example the Desktop scaling seems to stay the same while Dolphin looks smaller with Nvidia. I can change the DPI in Optimus Manager, but that only affects some parts (e.g. SDDM) but not others like Dolphin. If it is important: I use KDE with a scaling factor of 150 %

Whats going wrong here? How do I have to set Optimus Manager up, that I have the same scaling and proportions, no matter what  GPU I use?

**Comment by tsxxxx** [comment]
I also encountered this problem.

**Comment by nwildner** [comment]
Hello all.

Please take a look at last comment of the following case 

- #208 

This might be a case wher QT is scaling up things when in `nvidia` mode and it is an expected behavior. 

You'll need to thinker with the `QT_SCREEN_SCALE_FACTORS` and look for any new display naming that nvidia might be putting on your screens like `eDP1` becoming `eDP1-1` for example.

That is completely out of control of `optimus-manager`.

Have a nice week ahead.
