### ISSUE TITLE
Support for setting static Nvidia GPU clocks via coolbits and X (pre-Turing GPUs)

### ISSUE THREAD

**Issue by LukeFernandes** [Askannz/optimus-manager#406]
I get >25W on idle when nvidia mode is on. I also get quite high wattage when playing old Steam games; the games don't demand high performance but the GPU is clocked much higher than it needs to be. I have a Pascal GPU, which means, as you know, no way to use RTD3 power management.

A few ways of getting around this are set out in this [tips and tricks Arch linux article](https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks).

Unfortunately, I can't power limit my GPU using nvidia-smi as it appears my GPU doesn't support that. However, I should be able to set static clocks using 'Registry Dwords':

Option "RegistryDwords" "PerfLevelSrc=0x2222" (sets to high performance mode)

I would like an option to set this in optimus-manager. I can't do this at the moment directly as optimus-manager auto-generates the X.org file...

**Comment by Doaxan** [comment]
Same problem, is there a way to solve it?

**Comment by nwildner** [comment]
Closing since there is a quick hack provided on this case.

Also, added these instructions to the wiki:

 - [Overclocking and fan control stay locked in hybrid mode, even though Coolbits are set](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#overclocking-and-fan-control-stay-locked-in-hybrid-mode-even-though-coolbits-are-set)
