### ISSUE TITLE
The built-in screen of the laptop stays black but I can still input my password or use monitors plugged to a video output.

### ISSUE THREAD

**Issue by meyerx** [Askannz/optimus-manager#410]
Laptop integrated monitor stays black (no cursor, no back lighting) after locking the screen / suspending. when on hybrid/nvidia mode. 
Switching to TTY doesn't activate the monitor. 
Switching to TTY and  back to GDM activate the monitor and restore a login screen most of the time (but not 100%).
External screen has a video output.
This issue does not happen on startup.

**System info**

- Your distribution: **Archlinux**
- Your desktop manager: **GDM**
- You display manager: **GDM/Xorg**
- Your laptop model: **Lenovo Thinkpad X1 extreme gen3**
- The version of optimus-manager you are using : **aur/optimus-manager 1.4-2**
- Your custom optimus-manager configuration: **tried many different settings without success - current conf:**
```
[optimus]
switching=bbswitch
startup_mode=auto
startup_auto_battery_mode=hybrid
startup_auto_extpower_mode=nvidia
pci_reset=no

[nvidia]
modeset=no
dynamic_power_management=fine

[intel]
driver=intel
DRI=2
```

**Logs**
switch: [switch-20210528T201504.log](https://github.com/Askannz/optimus-manager/files/6564314/switch-20210528T201504.log)
deamon: [daemon-20210528T201504.log](https://github.com/Askannz/optimus-manager/files/6564317/daemon-20210528T201504.log)

**Comment by DenisValcke** [comment]
Have you tried this?

**Comment by meyerx** [comment]
Hi Denis,
Yep, but it didn't help. Thanks for the input though.

**Comment by nwildner** [comment]
Sup folks.

This is one of the lingering cases with more than 3 years of life, and some of the issues originally reported here might not be reproducing anymore. We highly recommend you to use optimus-manager-git package and updated Kernel, Distibution and Nvidia driver versions.

For this case in particular, please track the following case which has the same symptoms and a more recent report regarding this matter:

 - #552 - When I switch to Nvidia, the built-in screen of the laptop stays black but I can still input my password or use monitors plugged to a video output.

This case will be closed as a duplicate but, feel free to collaborate on that newer case if this issue is still persisting.

Have a nice week.
