### ISSUE TITLE
Idea: Having an option to switch to nvidia once input is detected (while using bbswitch)

### ISSUE THREAD

**Issue by nikp123** [Askannz/optimus-manager#42]
Anyway I noticed that while plugging in HDMI connector on my GTX 960M that it creates an ACPI event (which you can catch using acpid). The event is as follows ``video/switchmode VMOD 00000080 00000000`` (without the K at the end, this makes it different from the switch video output button on laptop keyboards).

Now the idea is to have that as a trigger to switch to an external graphics card while using bbswitch (because loading in nouveau is still using the GPU) 

I have made a demo script that will restart the session with the nvidia gpu once an input is detected.
To set this up:
```
pacman -S acpid unzip wget
wget https://github.com/Askannz/optimus-manager/files/2753325/handler.zip
unzip handler.zip
mv handler.sh /etc/acpi/handler.sh
chmod +x /etc/acpi/handler.sh
systemctl start acpid
```

Now plug in the HDMI (or any other video input for that matter) and it should work.
If it doesn't, try tracking ACPI events and see if anything happens if you plug in your video input. That way we can try to make it universal across all optimus laptops. Cheers.

EDIT: I forgot to mention that this is indeed a hardwired GPU, there is no way to use the HDMI with the intel driver.

**Comment by Askannz** [comment]
So, to be sure I understand : you want to trigger a GPU switch if a HDMI output is detected and optimus-manager is not configured to use nouveau (because if it is using nouveau, then the HDMI output should work already). Is that correct ?

I think it would be way too dangerous to do that without at least some kind of confirmation box. Remember, it forces all application to quit, and I don't want someone to lose unsaved work because he forgot about optimus-manager and plugged a HDMI cable.

The best way to implement your idea would be to have a box pop up when you plug a video cable, saying "Hey, if you want to use that video output, you'd better switch to Nvidia mode", and offering a button to switch. But we may be overstepping on the desktop manager here, so I'm not sure if it's worth it. Not to mention users may not have the acpid daemon enabled (I didn't for instance).

At least the ACPI event seems somewhat standard, I can also see `video/switchmode VMOD 00000080 00000000` as well when using `acpi_listen` (only in Intel mode though. The event does not happen in Nvidia mode).

**Comment by nikp123** [comment]
@Askannz I managed to make a script that does that job with least amount dependencies. So anyway you need the following: acpid, zenity, sudo and bash (and std. GNU utils obviously). That's it!

So download and extract the following on root: [switch_on_new_input.tar.gz](https://github.com/Askannz/optimus-manager/files/2756223/switch_on_new_input.tar.gz)

Enable acpid daemon, and that's it.

Of course this isn't the final solution, but I'm just showing that it can be done with little to no new dependencies/bloat introduced.

If you can just track ACPI events from python (that i almost have zero knowledge about) just run the script located at /etc/optimus-manager/handle_video_input.sh,  give it acpi paramaters and it would do the job.

**Comment by Askannz** [comment]
After leaving this issue stall for months I've decided not implement this feature.

While it would be nice if it worked 100%, in practice introducing both GUI elements _and_ ACPI events tracking to optimus-manager is a lot of effort (not to mention a huge source of bugs) for minimal gain : people using this software are generally aware of the limitations of the intel mode, and having a pop-up reminder might irritate them more than anything else.

Thanks for your input though, and sorry if your work didn't end up being used in the end.

**Comment by nikp123** [comment]
No problem, it's just a discovery that I wanted to implement because I've found this out by accident. Also I found out that nouveau+modesetting already uses this, so you'll get power saving either way. You can recommend that people try if nouveau+modesetting saves battery life when there's no PRIME apps running and when there's no external screen plugged in.

I was basically just fixing a non-existant problem.

Also there's no problem about my work not being used. I throw away 40% of my code that I write anyway.
