### ISSUE TITLE
After power management guide, it still tells me I have not configured a power mode setting.

### ISSUE THREAD

**Issue by trusktr** [Askannz/optimus-manager#421]
I followed the [guide to power management options](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options). After running `optimus-manager --temp-config ~/optimus-tmp.conf`, when I try changing GPUs I still get the same popup that tells me I have not configured an option.

Seems something is missing from that wiki page.

**Comment by trusktr** [comment]
Any idea what that is?

**Comment by nwildner** [comment]
Hello @trusktr  Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Can you please provide more details on this case(kernel version, nvidia driver version, linux distribution, optimus-manager.conf and the optimus-tmp.conf files, any other relevant logs)

Let me know if this issue is still relevant to you ok?

Have a nice week.
