### ISSUE TITLE
software vsync doesn work

### ISSUE THREAD

**Issue by jaggen** [Askannz/optimus-manager#43]
Hi,

I am a beginner so some things can be incomprehensible but:

I don't have problem with stuttering or bad performance. When i have turned on modeset, game ( eg banished via proton) runs fast but i have image waving. It's normal results from a large amount of FPS. In game vsync option doesnt take effect.

disabling the modeset gives mi bad performance so i skip this option.

is there a way to software (in-game) forcing vsync or is it closely related to prime synchronization?

greets!
Paul/Jaggen

**Comment by Zeioth** [comment]
This is not related with optimus-manager, but leaving that aside:

You can force Vsync for any game using [libstrangle](https://gitlab.com/torkel104/libstrangle). If you find it too hard, then keep an eye on the next version of Lutris, we are implenting this.

Cheers.

**Comment by Zeioth** [comment]
You can also try to limit the FPS of your game to the refresh rate of your screen (usually 60). That way you will be able to keep high performance, and the stuttering will be imperceptible.

**Comment by Zeioth** [comment]
For future questions of this kind I'd recommend you [stack overflow - arcade](https://gaming.stackexchange.com/).

**Comment by Askannz** [comment]
The problem may actually be loosely related to optimus-manager, because I've just found out that it may not be enabling Prime Sync correctly.

Until now, I thought that having optimus-manager enable modesetting in the driver was enough to enable PRIME Sync and get rid of tearing. I was comforted in this thought because because after doing so xrandr indeed reports `PRIME Synchronization: 1`.

However, I still see a bit of tearing on my machine, and after reading some sources I'm not so sure anymore that Prime Sync is actually works with this method. It may be necessary to [also add the nvidia modules to the initramfs](https://wiki.archlinux.org/index.php/NVIDIA#DRM_kernel_mode_setting).

You could try that @jaggen, but please not that I don't know how well that plays with GPU switching.

I hope someone with more knowledge can shed some light on the matter ; I'll try to conduct some tests myself to be sure.

**Comment by kuroni** [comment]
In this case though, screen tearing is not the result of high FPS. [This is a really good read on this topic](https://devtalk.nvidia.com/default/topic/957814/linux/prime-and-prime-synchronization/). **TL;DR**: Traditional VSync only sync the OpenGL video output and the NVIDIA GPU's video memory, but not between the NVIDIA GPU's memory and the Intel GPU's display. PRIME Sync offers both synchronizations, therefore fully synchronize the video output and the display.

Apart from the PRIME Sync technology, I haven't been able to find anything that works as well but minimalizes the PRIME's performance drop. As of now, I just ditch PRIME Sync and get use to the screen tearing :(

**Comment by Askannz** [comment]
So I don't know if anyone is still following this issue, but I made some testing on my own and I can confirm that enabling modesetting in the driver is enough to get rid of tearing ; no need to add the nvidia modules to the initramfs.
