### ISSUE TITLE
Ly Compatibility

### ISSUE THREAD

**Issue by nix-enthusiast** [Askannz/optimus-manager#430]
Hi.
Is Ly compatible with optimus-manager ?

**Comment by nwildner** [comment]
Hello @nix-enthusiast . Are you talking about [fairyglade/ly](https://github.com/fairyglade/ly)  Login Manager?

There is a [custom login manager](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#my-display-manager-is-not-sddm-lightdm-nor-sddm) wiki page that could be handy but since there are not really many active `ly` users participating here, there is no much of visibility. To be honest, I didn't even knew about this login manager, and I'm using Linux on laptops for something that dates back to 2005.

Feel free if you want to contribute by sending patches to that specific login manager in the future if you think some feature is missing.

Have a nice week ahead.
