### ISSUE TITLE
Nvidia mode: optimus-manager not loading xorg amdgpu driver

### ISSUE THREAD

**Issue by CygnusTerminal** [Askannz/optimus-manager#443]
**Describe the bug**
When setting nvidia mode, optimus-manager refuses to set xorg's amdgpu driver for my integrated gpu.

**System info**
Please include :
- Your distribution: Archlinux
- Your desktop manager: KDE
- You display manager: SDDM
- Your laptop model: 82EY IdeaPad Gaming 3 15ARH05
- The version of optimus-manager you are using : latest git from AUR
- Your custom optimus-manager configuration file:

[amd]
DRI=3
driver=amdgpu
tearfree=

[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
dynamic_power_management=fine
ignore_abi=yes
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=hybrid
startup_auto_extpower_mode=nvidia
startup_mode=auto
switching=none

**Logs**
[daemon-20211013T180659.log](https://github.com/Askannz/optimus-manager/files/7341497/daemon-20211013T180659.log)
[switch-20211013T181656.log](https://github.com/Askannz/optimus-manager/files/7341498/switch-20211013T181656.log)

**Comment by nwildner** [comment]
@CygnusTerminal . Is this issue still happening using `optimus-manager-git` ?

Since the last comment on this case was from 2,5 years ago and a lot has changed in many aspects of multiple software(nvidia, optimus-manager, linux), we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.
