### ISSUE TITLE
Run Xorg on Integrated graphics instead of dedicated GPU in Hybrid mode

### ISSUE THREAD

**Issue by Soupy710** [Askannz/optimus-manager#449]
Is there any way I can get Xorg to run on integrated graphics instead of my nvidia gpu in hybrid mode?

**Comment by Gigas002** [comment]
I have exactly the opposite question: how can I run Xorg on dedicated GPU in hybrid mode?

**Comment by Bestest-Coder** [comment]
I would like to know this as well, I think it's stopping the power management from fully shutting off my nvidia gpu and meaning I don't actually get full power save

**Comment by Soupy710** [comment]
I would suggest you use bbswitch as the switching method and use integrated mode for better battery life... Bbswitch completely disables the graphics card whereas the default switching method keeps it turned on even in integrated mode. That's what I did...

**Comment by mysteryx93** [comment]
Is bbsswitch Bumblebee? Was just discussing this with someone knowledgeable and he said setting up Bumblebee would result in some Linux performance loss. Correct me if I'm wrong.

**Comment by Soupy710** [comment]
Bumblebee internally uses bbswitch to switch on/off the graphics card. Yeah even I heard bumblebee is not that stable(prolly read this in arch wiki). I would suggest you use Optimus-manager with bbswitch to switch off/on the graphics card. I've been using this for around 4 months and it works flawlessly and I think it's the best you can do...

**Comment by Askannz** [comment]
> Is bbsswitch Bumblebee? Was just discussing this with someone knowledgeable and he said setting up Bumblebee would result in some Linux performance loss. Correct me if I'm wrong.
bbswitch was initially created for the bumblebee project but it's an independent module that can work on its own. There's no real reason to use bumblebee nowadays, not since Nvidia added proper driver support for Optimus. optimus-manager doesn't rely on bumblebee at all.

To answer the initial questions:

> Is there any way I can get Xorg to run on integrated graphics instead of my nvidia gpu in hybrid mode?
It...already does? That's the point of hybrid mode

> I have exactly the opposite problem: how can I run Xorg on dedicated GPU in hybrid mode?
Then you would basically achieve the "nvidia" mode. There's no possible power savings here since your card would have to stay on rendering the Xorg desktop.
