### ISSUE TITLE
Optimus Manager doesn't shutdown on intel

### ISSUE THREAD

**Issue by another-dark-knight** [Askannz/optimus-manager#46]
**Describe the bug**
When I try to shut down my system using intel, the system hangs. I need to force it. The startup script is nvida and it boots just fine. Futher if I switch back to nvidia from intel, the system hangs, and on force reboot the display manager fails to start. I then have to chroot into the system, disable the display manager and use plain old startx and it works just fine
When I switch to intel and use nvidia-smi the terminal hangs and doesn't give me an immediate answer unlike my friend's laptop which shows that the driver isn't loaded

**System info**
Please include :
- Archlinux
- i3-gaps
- Sddm and Lightdm(same issue)

**Logs**
- Display manager : https://pastebin.com/SQdtvYU2
- Daemon : https://pastebin.com/3U1PMhV4

**Comment by Askannz** [comment]
> on force reboot the display manager fails to start. I then have to chroot into the system, disable the display manager and use plain old startx and it works just fine

That's probably another occurrence of [this bug](https://github.com/Askannz/optimus-manager/issues/30#issuecomment-455156359). It's fixed in master but not released yet.

The other issues sound like an ACPI problem. Unfortunately these kinds of problem can be quite hard to pinpoint, so here are few things you can try :
- disabling PCI reset and PCI power control in the config file
- changing switching mode to bbswitch
- try one of the fixes suggested in [this GitHub issue](https://github.com/Bumblebee-Project/Bumblebee/issues/764),if you can find your laptop model there

Also, if the hang happens again and you have to force reboot, then grab the kernel log from the previous boot with `journalctl -k -b-1 --no-pager`. With some luck there will be some clues about the root issue there.

**Comment by spandan2** [comment]
Thank you ! I will wait for the master repo to become a part of your release

**Comment by Askannz** [comment]
(Late reply 'cause I was on leave)

> What is the problem with nouveau?
I don't really know, laptop manufacturers like to do their own things with ACPI, and I'm guessing some of those don't play nice with the nouveau driver.

If you have time, could you provide the kernel log of the hang, as I explained above ? It would help me identify similar problems in the future.

> And is there any disadvantage of using bbswitch?
The bbswitch module has been written a long time ago and isn't compatible with some newer laptop models. Also, one major disadvantage of turning the Nvidia card off with bbswitch is that you cannot use any output connected to this card anymore, because it's really, completely turned off.

This can have advantages though : on my machine, using the bbswitch method results in a much lower power consumption than the nouveau method. I don't know why, perhaps the default PCI power management stuff does not work with that model.
