### ISSUE TITLE
optimus-manager --switch from sudo script

### ISSUE THREAD

**Issue by mysteryx93** [Askannz/optimus-manager#465]
If I run this command from the shell, it works and logs out

    optimus-manager --switch integrated --no-confirm

If I put that in a script file, and run the script as sudo, it fails.

Even if I run as current user in the script, it still fails to close the session.

    #!/bin/bash
    su - hanuman -c 'optimus-manager --switch integrated --no-confirm'

My guess is that it's creating a new user session, and shutting down that temporary session. That would explain why it fails. Restoring to hybrid fails even more with an error.

How can I switch mode from a sudo script?

**Comment by mysteryx93** [comment]
I ended up restarting the whole `display-manager.service`. Not sure whether it's the best method, but it works.

    optimus-manager --switch --no-confirm hybrid
    systemctl restart display-manager.service

**Comment by nwildner** [comment]
Closing this since it might not be related with `optimus-manager` itself but, the way `su - user` handles user session, and it will be really hard to handle user sessions inside a script and also investigate that from the optimus-manager side. 

Please check out this solution on StackExchange regarding a similar issue:
 - [How do I use su to execute the rest of the bash script as that user? - Answer 1](https://stackoverflow.com/a/24696790)

Cheers
