### ISSUE TITLE
Does it work with gwe?

### ISSUE THREAD

**Issue by michaldybczak** [Askannz/optimus-manager#48]
There is a nvidia tweaker GUI utility "green with envy", called shortly gwe. I don't plan to mess with my GPU but I was just curious what are the options so I installed it. I was about to start it then I recalled that we shouldn't run nvidia settings program.

So how is with gwe? Is it safe to launch it? Is it safe to use it? Even if not for me, we should have this info in readme, because I have a feeling that gwe will become a standard app installed on many nvidia computers.

Thanks

**Comment by Askannz** [comment]
> I was about to start it then I recalled that we shouldn't run nvidia settings program.

Nonono, running `nvidia-settings` is fine as long as you don't use the "Save to X configuration" button or run `nvidia-xconfig`.

Gwe should be perfectly compatible with optimus-manager as long as you run it while you're in Nvidia mode (if you don't it'll probably just bail out because it can't find the nvidia driver). In fact, his creator asked me to test an early build some time ago.

**Comment by michaldybczak** [comment]
Thanks for the info.
Please, add this to readme just in case and the topic is closed :).
