### ISSUE TITLE
Display freezes after about five minutes when switch to NVIDIA

### ISSUE THREAD

**Issue by yashlakhtariya** [Askannz/optimus-manager#497]
I have Ryzen 5 5600H with iGPU and GeForce RTX 3050 as discrete GPU. When I switch to NVIDIA using optimus manager, my display freezes after about 5 minutes and unfreezes randomly, then again freezes and the loop continues. Please help me fixing this issue.

**Comment by Trqhxrd** [comment]
Same for me. I couldn't confirm it in hybrid mode yet but it definitely happens in NVIDIA only mode. I also have a 3050 Ti Mobile and a Ryzen 5 5600H. [This](https://pastebin.com/STKT8vzU) is my config. I don't really know what's causing the lags. I'll try different combinations of the `dynamic_power_management` and `options=overclocking`.

**Comment by nwildner** [comment]
@yashlakhtariya  Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Also, did you have the time to implement the workaround/fix provided by @ItsLiyua , since his laptop seems to bundle a hardware that is similar to yours regarding GPU+CPU?

Let me know if this issue is still relevant to you ok?

Have a nice week.
