### ISSUE TITLE
what drivers to install and what to block?

### ISSUE THREAD

**Issue by Khorkhe** [Askannz/optimus-manager#5]
Hello,
so far I have been blocking the nouveau / nvidia drivers with modprobe.  I suppose these should be unblocked?  What about xf86-video-intel, should it be installed?

If you could give a little more information on those prerequisites needed before using the optimus manager, it would be amazing!
Thanks for the great work :)

**Comment by Askannz** [comment]
Hi,

optimus-manager adds its own modprobe config files to blacklist nvidia and nouveau modules, so it's not going to hurt if you leave yours.

Blacklisting only prevents the modules to be loaded at boot time though, that's why the program is able to load them dynamically later.

About xf86-video-intel, I don't have it installed on my system, so I guess it's not needed 🤷

You're right about the prerequisites, I should add some clarifications in the README.

**Comment by philmmanjaro** [comment]
**xf86-video-intel** is on most hardware not recommended to be installed. Intel hardware also works just fine with falling back on the modesetting driver for fourth generation and newer GPUs.

**Comment by Khorkhe** [comment]
unfortunately, since upgrading Arch around early November, optimus-manager stopped working for me and I still have not been able to run since.
Any chance to get some assistance? 

Running Arch 5.0.0, with Intel HD 630 and NVIDIA GTX 1050 Mobile, no login manager (plain tty) and awesomeWM.
Around 6 months ago, optimus-manager was working great simply manually killing Xorg server, starting the service and switching GPU.
sometime later, after an upgrade, switch started giving an error. Now, few upgrades later, no error show up but the GLX command always returns SGI.

I'd be grateful for help to get it back up and running.
Thanks!
