### ISSUE TITLE
In hybrid mode Nvidia gpu doesn't use full vram

### ISSUE THREAD

**Issue by abhijayts** [Askannz/optimus-manager#503]
I had optimus-manager setup along with optimus-manager-qt and did not notice it until recently when playing a game in hybrid mode when it said that the graphics settings were not optimised as it was using more than available vram. My Nvidia gpu (1660 Ti)
 has 6gb vram but only about 2-4 gb is available, it varies everytime but never uses full 6 gb. This only happens in hybrid mode because when running the same game in Nvidia mode, it shows that 6 gb is available. Please fix this as in hybrid mode you have an advantage that the inferior gpu tasks can be handled by the integrated gpu and the demanding games can be run using Nvidia gpu.

My laptop configuration.
OS: Manjaro Linux x86_64 
Host: OMEN Laptop 15-en0002ax 
Kernel: 5.15.48-1-MANJARO 
Resolution: 1920x1080 
CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz 
GPU: AMD ATI 06:00.0 Renoir
GPU: NVIDIA GTX 1660 Ti

My optimus-manager configuration settings are attached below.
[optimus-manager.txt](https://github.com/Askannz/optimus-manager/files/8935900/optimus-manager.txt)

Much obliged.

**Comment by nwildner** [comment]
Sub @abhijayts . Are you still facing this issue with more recent kernel+nvidia and using `optimus-manager-git` ?

Also, please follow this thread on Nvidia forum: [VRAM Allocation Issues](https://forums.developer.nvidia.com/t/vram-allocation-issues/239678). This might not be related entirely with `optimus-manager` but, with the way hybrid graphics work on nvidia itself.

Since this issue isn't active for the last 2 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided. We're dealing with backlog here to try to keep `optimus-manager` in a good shape and active as a project.

Have a nice week ahead.

**Comment by abhijayts** [comment]
The issue has been resolved. You may close it. Thank you.
