### ISSUE TITLE
"GPU setup attempt failed at Xorg pre-start hook" after Manjaro Kernel Upgrade to 6.0.0rc7-1

### ISSUE THREAD

**Issue by BitByteShark** [Askannz/optimus-manager#522]
Optimus-manager (1.4+r12-2 from community repository) worked fine on my Laptop (Legion 5 Pro 16ACH6H with RTX 3070) with Manjaro (KDE) on Kernel 5.19.13-1.
On boot into Kernel 6.0.0rc7-1 Optimus-manager wouldn't start. I retried with Kernel 5.19.13-1 and on there it still works.

optimus-manager --status gave me:

> ERROR: the latest GPU setup attempt failed at Xorg pre-start hook. 
> Log at /var/log/optimus-manager/switch/switch-20221008T173430.log 
> Cannot execute command because of previous errors.

with the Log Output:

> [8] INFO: # Xorg pre-start hook
> [8] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'hybrid', 'current_mode': N
> one} 
> [8] INFO: Requested mode is: hybrid 
> [24] INFO: Available modules: ['nouveau'] 
> [24] INFO: Unloading modules ['nouveau'] (if loaded) 
> [26] INFO: switching=none, nothing to do 
> [42] INFO: Loading module nvidia 
> [43] ERROR: Xorg pre-start setup error 
> Traceback (most recent call last): 
>   File "/usr/lib/python3.10/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main 
>     setup_kernel_state(config, prev_state, requested_mode) 
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 22, in setup_kernel_state 
>     _nvidia_up(config, hybrid=(requested_mode == "hybrid")) 
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 95, in _nvidia_up 
>     _load_nvidia_modules(config, available_modules) 
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 164, in _load_nvidia_modules 
>     _load_module(available_modules, "nvidia", options=nvidia_options) 
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 241, in _load_module 
>     raise KernelSetupError( 
> optimus_manager.kernel.KernelSetupError: module nvidia is not available for current kernel. Is the correspondi
> ng package installed ? 
> [43] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present) 
> [43] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20221008T173430', 'requested_mode': '
> hybrid'}

I hope I can help, I will try to provide all the info if needed but I am no Linux wizzard so I might need some hints :)

**Comment by Za-rodnuiu** [comment]
similar issue after archcraft. here is the terminal message:

ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20221125T202130.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Cannot execute command because of previous errors.

and here is the log:

[switch-20221125T202130.log](https://github.com/Askannz/optimus-manager/files/10095474/switch-20221125T202130.log)

**Comment by chujDK** [comment]
i install the nvidia driver manually through `NVIDIA-Linux-x86_64-525.85.05.run` script. and the same issue occurs. seems the kernel update broke the driver. i solve this problem by reinstall the driver (rerun the `NVIDIA-Linux-x86_64-525.85.05.run`)

**Comment by nwildner** [comment]
Sup @BitByteShark . Did you had the time to upgrade your drivers to a more recent version and use `optimus-manager-git`? As reported by @chujDK , looks like this is a nvidia side bug.

Since this issue isn't active for the last year ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided.

Have a nice week ahead.
