### ISSUE TITLE
External monitors connected via TB4 dock not detected on boot / resume

### ISSUE THREAD

**Issue by lohedges** [Askannz/optimus-manager#526]
**Describe the bug**

Hello there,

Many thanks for this excellent program, which has saved me from many hybrid graphics related headaches over the years. I have recently started using a Thinkpad Thundebolt 4 Workstation Dock and am discovering that my two external monitors, which are connected to the dock via DisplayPort, appear as _disconnected_ on boot/login. After disconnecting and reconnecting the Thunderbolt cable from the laptop, the external displays are detected and I can then connect. Once connected, the display connection is lost again if I suspend the laptop. I was previously using a Thinkpad Thunderbolt 3 Workstation Dock and everything was working without issue.

I reported the issue on the Arch Forum [here](https://bbs.archlinux.org/viewtopic.php?id=280771) and, after some debugging, discovered that the external displays would  connect on login if I disabled the `modeset` option in the `nvidia` section of the `optimus-manager` configuration file. However, after doing so I am experiencing frequent graphical glitches, i.e. flickering and display drop-outs.

I appreciate that it is likely that this isn't specifically an `optimus-manager` issue, but I was wondering if anyone else had experienced similar, or had suggestions for what to try. I am guessing that it is an NVIDIA or Thunderbolt driver issue. Perhaps I need to adjust things so that certain NVIDIA related modules are loaded early enough?

Many thanks.

**System info**

- Distribution: Arch LInux
- Display manager: DWM
- Thinkpad P1 Gen 2/5
- optimus-manager 1.4-4
-  optimus-manager (below):
```
[intel]
DRI=3
driver=modesetting
modeset=yes

[nvidia]
PAT=yes
ignore_abi=no
modeset=yes

[optimus]
pci_power_control=no
pci_remove=no
pci_reset=function_level
switching=bbswitch
```

**Comment by Magicrafter13** [comment]
Manjaro user here, also experiencing issues with a thunderbolt dock with attached monitors. Notably in Nvidia mode only, not in hybrid mode.

This is a fresh install and all desktops should be the same:
![20221115_193339](https://user-images.githubusercontent.com/29127566/202078520-bc8e5ff0-6244-4670-b427-9fe5e6fb744e.jpg)

This is an issue I was experiencing before reinstalling and I'm sad to find out it's optimus-manager at fault since I need this program to use my GPU at all, but I'm at least happy I've discovered the cause. Before I had 3 different wallpapers, one for each screen. If I login with the dock connected, screen 2 has screen 1's wallpaper and screen 3 has screen 2's wallpaper, while screen 1 has no wallpaper (like in the image). Everything is shifted left. If I wait to attach the dock until after login everything works, but this is not ideal for several reasons.

Actually I stand corrected, it used to work if I plugged in after login, but it appears to have the same issue as before I reinstalled which it started doing recently, making it impossible to work normally:
![20221115_193550](https://user-images.githubusercontent.com/29127566/202078549-4fb5eab0-1d93-46bd-9fce-db2efb92ac10.jpg)

Laptop display is shifted up, and the external displays aren't even on. I was able to fix this by removing everything at ~/.local/share/kscreen and relogging (with the dock unattached) so KDE does seem at least partly to blame. I'm still kinda afraid to move the laptop display back down (it's shorter resolution that the external displays so I line up the bottom corners instead of the top corners). But we'll see. After this "fix" the login screen is still messed up (see below) but thankfully the screens are fine when I log in. This whole system seems very fickle lol. I wonder if we'll have a better time when we've all switched to Wayland...
![20221115_194537](https://user-images.githubusercontent.com/29127566/202078678-547c763a-b1f8-4a1e-b8fd-5f8fa6ff9586.jpg)

**Comment by ok-nick** [comment]
I don't use `optimus-manager` but I have the same issue. Sometimes one external display turns on, sometimes the other, sometimes both. On the fortunate occasion, I can get a long streak of both of them turning on.

I can say though, ever since I enabled early loading [DRM](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting), it doesn't work for either monitors, ever.

@lohedges Your link to the arch forum is not the correct page.

**Comment by lohedges** [comment]
@ok-nick: Thanks, I've now fixed the forum link.

**Comment by nwildner** [comment]
@lohedges . Is this issue still reproducing after upgrading the firmware of your Thunderbolt 4 docking? 

Is this case still relevant to you?

**Comment by lohedges** [comment]
No, it's no longer relevant. I ended up selling the TB4 dock and reverting to using the TB3 versions, which works fine. Feel free to close.
