### ISSUE TITLE
Best power management for Ryzen 5 Gtx1650?

### ISSUE THREAD

**Issue by RuizSenior** [Askannz/optimus-manager#566]
I have an Acer nitro 5 with an AMD Ryzen 5 4600 and an Nvidia GTX 1650. I would like to know which would be the best power management

**Comment by gaianoseworthy** [comment]
@RuizSenior Not a developer, but a user for many years now. The long and short is that this will depend on your system and posting specs is a good idea. That being said, for general advice, I highly recommend reading the [Guide to Power Management Options](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options), for a TL;DR:
- You can set it up to use integrated on battery and dedicated on external
- Or, you can set up hybrid, so it maximizes efficiency until power is needed and autoswitches to NVIDIA for power

In any case, for power switching, I recommend you set it to use Nouveau with PCI_reset=no, PCI_power_control=yes, PCI_remove=no. This is the default (step 2 in the link) that runs most efficiently. 

If, for some reason, that doesn't work, go through the other options in the link. Again, depending on your system, I recommend you grab Optimus Manager QT so that you have a graphical interface to make life easier.

For added notes, make sure you read the V1.3.1 readme, ESPECIALLY if you use Manjaro as it has a **required** step in there and gives a lot more useful information.

**Comment by nwildner** [comment]
Closing this since the discussion seems to have been ended.

Also, other power management tools like `tlp` or `laptop-mode` should be used in conjunction with `optimus-manager-git` for best handling battery drain.
