### ISSUE TITLE
truble compiling on fadora 40

### ISSUE THREAD

**Issue by nagaisa** [Askannz/optimus-manager#576]
i seam to have truble compiling, after running "cmake -D CMAKE_BUILD_TYPE=Release -D WITH_PLASMA=ON . ." i get this:

```
CMake Error at CMakeLists.txt:24 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by aszrul** [comment]
Try install this

`sudo dnf install extra-cmake-modules`

That ECM is Extra CMake Modules which is why you got missing package configuration error.

References:
1. https://api.kde.org/frameworks/extra-cmake-modules/html/index.html
2. https://packages.fedoraproject.org/pkgs/extra-cmake-modules/extra-cmake-modules/index.html

**Comment by es20490446e** [comment]
Reopen if the suggested fix doesn't work for you.
