### ISSUE TITLE
Set LIBVA_DRIVER_NAME(iHD/i965/nouveau, vdpau) and VDPAU_DRIVER(va_gl/nouveau, nvidia) automatically for currently used GPU. 

### ISSUE THREAD

**Issue by Howard-00** [Askannz/optimus-manager#81]

**Comment by Askannz** [comment]
Care to provide a bit more info there ? I'm not familiar with video decoding libraries, what do those variables do and why are they necessary ?

**Comment by takov751** [comment]
Easiest way of getting familiar with these source: [https://wiki.archlinux.org/index.ph;p/Hardware_video_acceleration](url)

But beware if your card is not from the GTX series than there is no NVENC ,so 
`vpau_driver has to be == va_gl`  and `vaapi should be ==vdpau` which means nvidia opengl backend used for Video encoding. 

In this case you would probably likely to use intel vaapi ,which might be a problem because libva uses the card0 and libva project does not implemented vaapi_device environmental variable yet.There are only a few app where you can define device(ffmpeg,obs,vlc etc) I would say it would be better define these in script after the gpu switch was made.And would be better defined by user or use case of deviceid(like blacklist)

**Comment by Askannz** [comment]
Dynamically setting environment variables system-wide (or session-wide, for that matter) is a pain, I don't really see a way to do it properly from optimus-manager (i'm open to suggestions though). It's probably best for the user to set those env vars manually.

**Comment by Askannz** [comment]
Closing since there isn't really any way to implement this.
