### ISSUE TITLE
Nouveau doesn't disables nvidia, bbswitch gives black screen on intel

### ISSUE THREAD

**Issue by magmast** [Askannz/optimus-manager#82]
**Description**
When I use default switching mode and switch to intel, nvidia gpu seems to be still running. But when I set switching to bbswitch as its described in FAQ and reboot I've got black screen. I was trying to fix that by blacklisting nouveau and adding `acpi_osi=! acpi_osi='Windows 2009' pcie_port_pm=off` but the result was the same. In both cases nvidia mode works.

**System info**
- Distro: Anarchy linux
- Desktop manager: XFCE4
- Display manager: LightDM
- Laptop: HP Pavilion Power 15 (15-bc402nw)

**Logs**
https://pastebin.com/4Fs9EuL8
There is some error at 104 line, but description isn't useful.

**Comment by Askannz** [comment]
Yeah, unfortunately GPU power switching on Linux is giant mess because of manufacturers not agreeing on anything. If you have already tried both nouveau and bbswitch, there is not much else I can suggest besides trying every solution from [here](https://github.com/Bumblebee-Project/Bumblebee/issues/764#issuecomment-499863562), or google your laptop model and see if there is a way to enable switching.

**Comment by magmast** [comment]
Thanks, I'll look at that.

**Comment by pexcn** [comment]
Same problem, any updates?

**Comment by gbytedev** [comment]
Have you guys tried setting `driver=intel` under the `[intel]` section of `/etc/optimus-manager/optimus-manager.conf`? That worked for me well with bbswitch.

**Comment by lan542662** [comment]
> 
> 
> Have you guys tried setting `driver=intel` under the `[intel]` section of `/etc/optimus-manager/optimus-manager.conf`? That worked for me well with bbswitch.

I use driver=modesetting, archlinux community suggest modesetting.

**Comment by Askannz** [comment]
Closing this issue because it's unfortunately very model-specific and I can't implement an universal fix.

Since v1.2 there has been some changes to the power management code that _might_ mitigate the issue, and I also wrote a [guide](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options) on how to choose the parameters that work best for you. Please refer to that.
