### ISSUE TITLE
Vulkan unavailable in Nvidia mode

### ISSUE THREAD

**Issue by ixrk** [Askannz/optimus-manager#93]
**Describe the bug**
Whenever I launch any Vulkan application while in Nvidia mode I get a black window or an error. This problem can be partially fixed by uninstalling `vulkan-intel` or setting environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`, but that is not a really practical solution because then I cannot use Vulkan in Intel mode anymore. 

**How to reproduce**

1. install `vulkan-intel`
2. run `vkcube` from `vulkan-tools` to test if Vulkan works
3. switch to Nvidia mode
4. run `vkcube` again

**Expected outcome**
beautifully rendered cube

**Actual outcome**
black window

**System info**
- Archlinux
- KDE
- SDDM

**Logs**
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3314874/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/3314875/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/3314876/prime_setup.log)

**Comment by Askannz** [comment]
That looks like the classic issue of games picking the first Vulkan driver they see instead of the dedicated GPU. Overwatch is a known offender for this on Optimus laptops.

What games have you tried ? I doubt this is an optimus-manager bug.

That said, it may be a good idea for optimus-manager to set `VK_ICD_FILENAMES` system-wide when switching GPUs, to prevent this kind of issues...I'll think about it.

**Comment by Askannz** [comment]
After some research, it looks like setting `VK_ICD_FILENAMES` system-wide is a pain in the arse...the only method that seems to work reliably is to put it in `/etc/environment`, but I'd rather not have optimus-manager edit that file automatically.

I tried putting it in a separate file in `/etc/environment.d/` but it just gets ignored for desktop applications (even though it's showing up in `systemctl --user show-environment`).

**Comment by Askannz** [comment]
I added a section in the FAQ about this issue. Nothing else I can do since it doesn't seem to be possible to dynamically set the env var system-wide.

**Comment by TymanLS** [comment]
Could it be possible to simply rename the Intel Vulkan driver config file when switching to Nvidia mode, then restoring the original name when switching back to Intel mode? 

For example, I'm currently doing this in `/etc/optimus-manager/xsetup-nvidia.sh`
```
# Disable the use of 64-bit Vulkan applications on the Intel iGPU
if test -f "/usr/share/vulkan/icd.d/intel_icd.x86_64.json"; then
    mv /usr/share/vulkan/icd.d/intel_icd.x86_64.json /usr/share/vulkan/icd.d/intel_icd.x86_64.json.bak
fi

# Disable the use of 32-bit Vulkan applications on the Intel iGPU
if test -f "/usr/share/vulkan/icd.d/intel_icd.i686.json"; then
    mv /usr/share/vulkan/icd.d/intel_icd.i686.json /usr/share/vulkan/icd.d/intel_icd.i686.json.bak
fi
```

and this in `/etc/optimus-manager/xsetup-intel.sh`
```
# Enable the use of 64-bit Vulkan applications on the Intel iGPU
if test -f "/usr/share/vulkan/icd.d/intel_icd.x86_64.json.bak"; then
        mv /usr/share/vulkan/icd.d/intel_icd.x86_64.json.bak /usr/share/vulkan/icd.d/intel_icd.x86_64.json
fi

# Enable the use of 32-bit Vulkan applications on the Intel iGPU
if test -f "/usr/share/vulkan/icd.d/intel_icd.i686.json.bak"; then
        mv /usr/share/vulkan/icd.d/intel_icd.i686.json.bak /usr/share/vulkan/icd.d/intel_icd.i686.json
fi
```

I'm using this as a hack-around since I don't want to have to manually set the environment variable every time, and it appears to work fine for me. Then again though, modifying files in `/usr` may not be the best idea either... any thoughts?
