### ISSUE TITLE
Question: bbswitch and nvidia-xrun

### ISSUE THREAD

**Issue by RidgeA** [Askannz/optimus-manager#94]
Hello!
I installed bbswitch to my laptop according to https://wiki.archlinux.org/index.php/Nvidia-xrun

Unfortunately, my HDMI output doesn't work (xrandr doesn't detect any HDMI output at all).
I want to try optimus-manager.

Do I have to uninstall bbswitch before installing optimus manager?
Would it help me to use secondary monitor via HDMI (I suppose, HDMI works via Nvidia card)?

**Comment by Askannz** [comment]
> Do I have to uninstall bbswitch before installing optimus manager?

bbswitch is actually an optional dependency of optimus-manager because it can be used as the power switching backend (it's not the default though). So no,there is no harm in leaving it.

> Would it help me to use secondary monitor via HDMI (I suppose, HDMI works via Nvidia card)?

If your HDMI output is connected to your Nvidia card (which is probably why xrandr doesn't see it), then yes, optimus-manager should allow you to use it.

**Comment by RidgeA** [comment]
Thank you @Askannz 

> So no, there is no harm in leaving it.
and I don't need to white-list modules back https://wiki.archlinux.org/index.php/Nvidia-xrun#NVIDIA_GPU_fails_to_switch_off_or_is_set_to_be_default ?

**Comment by Askannz** [comment]
optimus-manager also puts the exact same blacklists in place : https://github.com/Askannz/optimus-manager/blob/master/modules/optimus-manager.conf

Doesn't hurt to have them twice, but it's unneeded.

**Comment by RidgeA** [comment]
Thank you !
